name = "Ressac"
uuid = "e9bcfb42-369a-4c89-a503-1a080b983652"
authors = ["Rodolphe Marbot <rododhendron@hey.com>"]
version = "0.1.0-DEV"

[deps]
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
TerminalUserInterfaces = "408767e4-586b-40c7-9657-f9758988469a"

[compat]
TerminalUserInterfaces = "0.8"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
