# Static docs + starter sketches surfaced through `:doc` and `:starter`.
# Goal: short, plain-language explanations a junior can read while live
# coding. Keep each entry one or two lines.

"""
    _PARAM_DOCS

Maps OSC param name → short prose description. Surfaced via `:doc <name>`.
The same map is reused by `:browse` to enrich hover info if we add it
later.
"""
const _PARAM_DOCS = Dict{String,String}(
    # Envelope
    "attack"      => "Time to reach full volume after a note triggers (sec). 0.01=instant, 0.5=soft fade in.",
    "release"     => "Time to fade out after the note ends (sec). 0.1=staccato, 0.5=normal, 2=long tail.",
    "sustain"     => "Level held while the note is on (0-1). Affects ADSR shape.",
    "hold"        => "How long the envelope stays at peak before release (sec).",
    "legato"      => "Note overlap (0 = no overlap, 1 = full hold). Use for connected lines.",
    # Filters
    "cutoff"      => "Filter frequency for the synth's internal filter (Hz). Lower = darker.",
    "resonance"   => "Filter resonance (0-1). Higher = more peak around cutoff, 0.5+ starts to whistle.",
    "lpf"         => "Low-pass filter (Hz). Cut everything above. <300 = sub only, 5000 = bright.",
    "hpf"         => "High-pass filter (Hz). Cut everything below. 200 = remove rumble, 1000 = thin.",
    "bandq"       => "Band-pass filter Q (resonance/width).",
    "bandf"       => "Band-pass filter frequency (Hz).",
    "hcutoff"     => "Synth-internal high-pass cutoff.",
    "hresonance"  => "Synth-internal high-pass resonance.",
    # Gain / mix
    "gain"        => "Volume multiplier. 1=neutral, 0.5=half, 2=double. Composes ×.",
    "pan"         => "Stereo position. 0=left, 0.5=center, 1=right (some setups: -1 to 1).",
    "n"           => "Note offset (semitones) for synths, or sample-variant index for sample banks.",
    "freq"        => "Raw frequency in Hz. Sets the synth's freq param directly (bypasses n→freq mapping).",
    "speed"       => "Playback speed. 0.5=octave down + slower, 2=octave up + faster. Composes ×.",
    # --- CORE CONCEPTS ---
    "cps"         => "Cycles per second — Ressac's tempo unit. 0.5 = 1 cycle / 2s (30 BPM @ 4 beats/cycle), 0.8 = ~48 BPM, 0.3 = 18 BPM. cps!(x) sets it live, :cps x is the TUI form.",
    "cps!"        => "cps!(x) — set the live scheduler tempo in cycles/sec. Equivalent to :cps x at the command line.",
    "cycle"       => "Ressac's time unit. Every pattern repeats once per cycle. A `p\"a b c d\"` produces 4 events evenly across one cycle.",
    "@dN"         => "@d1, @d2, ... @d64 — slot macros. `@d1 pattern` installs `pattern` at slot d1; assigning a new value re-evals.",
    "d!"          => "d!(:dN, pattern) — set a slot from Julia code (REPL or :julia hooks). Same effect as @dN.",
    "unset!"      => "unset!(:dN) — stop slot dN. Equivalent to commenting the line with `m`.",
    "hush_all!"   => "hush_all!() — stop every slot. Panic button.",
    "slot"        => "A named pattern channel (:d1 to :d64). The scheduler queries each slot every cycle and ships its events to OSC.",
    # --- COMBINATORS (pattern transforms) ---
    "pure"        => "pure(v) — pattern that fires v once per cycle. The atom you build on.",
    "silence"     => "silence(T) — empty pattern of type T. Useful as a placeholder.",
    "fast"        => "fast(n, p) or `p |> fast(n)` — compress time ×n. fast(2) plays twice in a cycle.",
    "slow"        => "slow(n, p) or `p |> slow(n)` — dilate ×n. slow(2) plays once over 2 cycles.",
    "density"     => "Alias for fast — TidalCycles compat.",
    "rev"         => "rev(p) — reverse events within each cycle.",
    "every"       => "every(N, f, p) — apply transform f every Nth cycle. e.g. every(4, fast(2)).",
    "stack"       => "stack(p, q, ...) — play patterns in parallel (layer them).",
    "cat"         => "cat([p, q, r]) — cycle through patterns, one per cycle.",
    "mask"        => "mask(p, q::Pattern{Bool}) — gate p by q. Where q is true, p plays.",
    "gate"        => "gate(:name, p\"1 0 0 1 …\") — substitute :name for every non-silence event of p. Short alias for rhythm masks.",
    "degree"      => "degree(x) — like n(x) but interprets x as a scale-degree in the current :scale (use `:scale minor` first).",
    # --- MINI-NOTATION (inside p\"…\") ---
    ""           => "p\"bd hh sn\" — mini-notation literal. Each whitespace-separated token = 1 event in the cycle.",
    "~"           => "~ inside p\"…\" — silence (no event for that slot).",
    "*"           => "name*N inside p\"…\" — repeat name N times inside its slot. p\"bd*4\" = 4 hits/cycle.",
    "!"           => "name!N — give name N times the weight (takes N slots).",
    "[]"          => "[a b] inside p\"…\" — sub-group (treated as one slot, recursively divided).",
    "<>"          => "<a b c> — alternation: a on cycle 0, b on cycle 1, c on cycle 2, repeat.",
    "()"          => "name(k,n) — Euclidean rhythm: k hits over n steps. p\"bd(3,8)\" = classic 3-against-8.",
    # FX
    "room"        => "Reverb send. 0=dry, 1=wet. Goes through SuperDirt's room reverb.",
    "delay"       => "Delay send. 0=dry, 1=wet.",
    "delaytime"   => "Delay time in beats. 0.25=16th, 0.5=8th, 1=quarter.",
    "delayfeedback" => "Delay regen (0-0.95). High = long tails.",
    "shape"       => "Waveshaper drive (0-1). Subtle saturation at 0.1, heavy distortion at 0.5+.",
    "crush"       => "Bit-crush depth (1=destroyed, 16=clean). 6-8 = lofi.",
    "coarse"      => "Sample-rate reduction. Higher = chunkier aliasing.",
    "vowel"       => "Formant filter, vowels :a :e :i :o :u. Makes things 'speak'.",
    "enhance"     => "Mid/treble enhancer (0-1).",
    # Modulation
    "accelerate"  => "Pitch sweep across the note (semitones/sec). Positive = up, negative = down.",
    "vibrato"     => "Pitch wobble amount.",
    "tremolorate" => "Tremolo speed (Hz).",
    "tremolodepth"=> "Tremolo depth (0-1).",
    "phaserrate"  => "Phaser sweep speed (Hz).",
    "phaserdepth" => "Phaser depth (0-1).",
    # Pitch
    "octave"      => "Octave offset.",
    "detune"      => "Detune amount (cents/0-1).",
    "slide"       => "Pitch slide between notes.",
    # Sample window
    "begin"       => "Sample start position (0-1).",
    "end"         => "Sample end position (0-1).",
    "cut"         => "Cut group: voices sharing the same positive int truncate each other.",
    # --- COMMON SYNTHDEF PARAMS (used in our starter template + common conventions) ---
    "rate"        => "LFO rate in Hz. 4 = 4 cycles/sec, 0.5 = slow swell, 16 = fast wobble.",
    "depth"       => "Modulation depth. For an LFO on cutoff: how wide the cutoff sweeps around `centre`.",
    "centre"      => "Centre / pivot value an LFO modulates around. Used together with `depth` for symmetric sweeps.",
    "center"      => "Alias for centre. American spelling.",
    "q"           => "Filter resonance/quality (inverse 'rq'). 0.1=sharp peak, 0.5=medium, 1=no resonance. Higher q = more whistle.",
    "rq"          => "Reciprocal Q for SuperCollider filters (RLPF, RHPF). 1.0=no resonance, 0.1=very resonant.",
    "out"         => "Synth output bus number. 0=master left, 1=master right. SuperDirt routes through DirtPan via this.",
    "decay"       => "Decay time in sec. ADSR's D — how long from peak to sustain level.",
    "damp"        => "Damping (0-1). In reverbs: high freq absorption. In drums: sharpness of the body.",
    "mix"         => "Dry/wet mix for FX (0=dry, 1=wet).",
    "modfreq"     => "Modulator frequency for FM synthesis.",
    "moddepth"    => "Modulator depth / amplitude for FM.",
    "velocity"    => "Note velocity (0-1). Often shaped into amplitude or filter cutoff.",
    "threshold"   => "Compressor / gate threshold (typically in dB or amp 0-1).",
    "ratio"       => "Compressor ratio (1=no compression, 4=4:1, ∞=limiting).",
    "feedback"    => "Delay or comb feedback amount (0-0.95). High = long tails / oscillation.",
    "freqshift"   => "Frequency shifter amount (Hz, signed).",
    "pitchshift"  => "Pitch shifter amount (semitones).",
    "spread"      => "Stereo spread / detuning amount.",
    "fade"        => "Fade-in or crossfade time (sec).",
    "size"        => "Reverb size / room size (0-1). Larger = bigger virtual space.",

    # ── Chaos plugin (control-rate Pattern{Float64} generators) ────
    "Chaos.lorenz"   => "Lorenz attractor (3D continuous). kwargs: σ=10, ρ=28, β=8/3, dt=0.01, axis=:x|:y|:z, steps_per_cycle=100, init=(x,y,z). Returns Pattern{Float64} to feed into set(...) or range_pat.",
    "Chaos.henon"    => "Hénon map (2D discrete). kwargs: a=1.4, b=0.3, axis=:x|:y, steps_per_cycle=64, init=(x,y). Returns Pattern{Float64}.",
    "Chaos.logistic" => "Logistic map (1D). kwargs: r=3.9, steps_per_cycle=64, init=0.5. r∈[3.57, 4] is chaotic.",
    "Chaos.rossler"  => "Rössler attractor (3D continuous). kwargs: a=0.2, b=0.2, c=5.7, dt=0.05, axis=:x|:y|:z, steps_per_cycle=100, init=(x,y,z).",
    "Chaos.standard" => "Chirikov standard map. kwargs: K=0.971635, axis=:p|:θ, steps_per_cycle=64, init=(p,θ). K≈0.97 is the chaos threshold.",
    "lorenz"   => "AUDIO-rate LorenzL UGen for @synth (sc3-plugins). Args: freq, σ, ρ, β, h, xi, yi, zi. For control-rate use Chaos.lorenz.",
    "henon"    => "AUDIO-rate HenonL UGen for @synth. Args: freq, a, b, x0, x1. For control-rate use Chaos.henon.",
    "logistic" => "AUDIO-rate Logistic UGen for @synth. Args: freq, paramA, x0.",
    "latoo"    => "AUDIO-rate Latoocarfian (Pickover) UGen for @synth. Args: freq, a, b, c, d, xi, yi.",
    "fbsine"   => "AUDIO-rate FBSineL UGen for @synth. Args: freq, im, fb, a, c, xi, yi.",
    "lincong"  => "AUDIO-rate LinCongL UGen for @synth. Args: freq, a, c, m, xi.",
    "quad"     => "AUDIO-rate QuadL UGen for @synth. Args: freq, a, b, c, xi.",
    "gbman"    => "AUDIO-rate GbmanL (Gingerbreadman) UGen for @synth. Args: freq, xi, yi.",
    "cusp"     => "AUDIO-rate CuspL UGen for @synth. Args: freq, a, b, xi.",

    # ── Reservoir plugin ──────────────────────────────────────────
    "Reservoir.adex"           => "Build an AdEx spiking-neuron reservoir. kwargs: N, params=ADEX_*, σ_noise (OU noise pA), τ_noise (ms), inhibitory_fraction, p_connect, W_gain, V_init=:rest|:scattered, seed.",
    "Reservoir.reca"           => "Build a RECA (cellular-automaton) reservoir. kwargs: N, rule (0..255), init=:single|:rand|:zero, boundary=:wrap|:zero, steps_per_cycle.",
    "Reservoir.spike_burst"    => "Route I — each spike fires a sineburst event at the neuron's mapped freq. kwargs: drive, layout, layout_args, lo, hi, burst_dur, gain, synth.",
    "Reservoir.pool_burst"     => "Route IV — pool N neurons into K bins, gain accumulates with spike count. kwargs: bins, frames_per_cycle, layout, drive, gain_per_spike, max_gain, burst_dur, mapping=:roundrobin|:hash.",
    "Reservoir.spectral_cloud" => "Route II — N additive partials per frame, amps from reservoir state. kwargs: bins, frames_per_cycle, layout, drive, amplitude_kind, amplitude_scale, overlap, synth.",
    "Reservoir.modulator"      => "Route III — read a scalar from one neuron as Pattern{Float64}. kwargs: neuron, kind=:auto|:V|:w|:spike|:density|:bit, scale, drive.",
    "Reservoir.rate_voice"     => "Route V — measured spike rate (Hz) → oscillator freq. A neuron firing at 200 spikes/sec → 200 Hz tone. kwargs: sources (Vector{Int}, Vector{Vector{Int}}, or :all), shape=:impulse|:saw|:sin|:pulse, frames_per_cycle, freq_scale, freq_offset, lo_freq, hi_freq, gain, overlap, drive, smoothing_frames.",
    "Reservoir.couple"         => "Build a CoupledReservoirs group from a vector of reservoirs. Followed by connect!() for projections. kwarg: output_idx.",
    "Reservoir.connect!"       => "Add a directional projection src → dst between members of a coupled group. kwargs: gain, p_connect, sign=:positive|:negative|:mixed, seed.",
    "Reservoir.record_history!" => "Opt-in spike history recording for the visual scope. record_history!(r, capacity). Set capacity=0 to stop.",

    # ── Drive helpers (reservoir) ─────────────────────────────────
    "drive_const"  => "drive_const(amp) → Function. Constant current to all neurons each step.",
    "drive_sin"    => "drive_sin(amp, period_steps; offset=0, phase=0) → Function. Sine wave, period in steps.",
    "drive_square" => "drive_square(amp, period_steps; duty=0.5, offset=0) → Function. On/off pulse train.",
    "drive_tri"    => "drive_tri(amp, period_steps; offset=0) → Function. Triangle wave.",
    "drive_ramp"   => "drive_ramp(low, high, period_steps) → Function. Sawtooth ramp.",
    "drive_burst"  => "drive_burst(amp, on_steps, every_steps; offset=0) → Function. Periodic bursts.",
    "drive_sum"    => "drive_sum(d1, d2, ...) → Function. Sum / layer multiple drive sources.",

    # ── AdEx parameter presets (Brette & Gerstner 2005) ───────────
    "ADEX_TONIC"          => "AdEx preset — tonic spiking (steady firing, no adaptation).",
    "ADEX_ADAPTING"       => "AdEx preset — adapting (initial rapid burst then slows as adaptation builds).",
    "ADEX_INITIAL_BURST"  => "AdEx preset — initial burst on stimulus onset then sparse.",
    "ADEX_REGULAR_BURST"  => "AdEx preset — repeating bursts on sustained input.",
    "ADEX_DELAYED_ACCEL"  => "AdEx preset — pause then accelerating spike rate.",
    "ADEX_DELAYED_BURST"  => "AdEx preset — pause then regular bursts.",
    "ADEX_TRANSIENT"      => "AdEx preset — brief onset firing then stops despite input.",
    "ADEX_IRREGULAR"      => "AdEx preset — chaotic dynamics near bifurcation.",
)

"""
    _PARAM_EXAMPLES

Maps the same names as `_PARAM_DOCS` to a list of one-line usage
examples surfaced by `:doc <name>`. Keep each line copy-pasteable —
the whole point is the user can drop it into the patterns pane and
press `e`. Not every entry needs examples; absence is fine.
"""
const _PARAM_EXAMPLES = Dict{String,Vector{String}}(
    "n" => [
        "@d1 :bd |> n(p\"0 3 5 0\")           # bd:0 bd:3 bd:5 bd:0 (sample variants)",
        "@d1 :wobble |> n(p\"0 3 7 12\") |> gain(0.7)   # root → m3 → fifth → octave",
        "@d1 :bass |> n(p\"<0 -5 7 -3>\")     # alternate the offset across cycles",
    ],
    "degree" => [
        "cps!(0.5); :scale minor",
        "@d1 :wobble |> degree(p\"0 2 4 7\") |> gain(0.6)  # scale-aware (no #s in mini-notation)",
    ],
    "gain" => [
        "@d1 p\"bd*4\" |> gain(0.8)",
        "@d1 p\"hh hh hh hh\" |> gain(p\"0.8 0.4 0.6 0.4\")  # accent pattern",
        "@d1 p\"sn\" |> gain(0.7) |> gain(1.4)             # composes ×, becomes 0.98",
    ],
    "pan" => [
        "@d1 p\"hh*8\" |> pan(p\"0.2 0.8\")    # ping-pong",
        "@d1 p\"bd\" |> pan(0.5)              # dead-center",
    ],
    "lpf" => [
        "@d1 p\"bd*4\" |> lpf(400)             # muffled kick",
        "@d1 :supersaw |> lpf(p\"<2000 800 4000>\")  # filter sweep across cycles",
    ],
    "hpf" => [
        "@d1 p\"oh*8\" |> hpf(6000) |> gain(0.5)   # tight click hat",
    ],
    "speed" => [
        "@d1 p\"bd*2\" |> speed(0.5)           # pitched down + slower",
        "@d1 p\"vinyl\" |> speed(p\"1 0.95 1 1.05\")  # turntable wow",
    ],
    "room" => [
        "@d1 p\"cp\" |> room(0.8) |> gain(0.6)",
    ],
    "delay" => [
        "@d1 p\"sn\" |> delay(0.6) |> delaytime(0.375) |> delayfeedback(0.5)",
    ],
    "cps" => [
        "cps!(0.5)        # 30 BPM at 4 beats/cycle, default",
        "cps!(0.75)       # ~45 BPM",
        ":bpm             # tap-tempo: 4 hits + Enter sets cps live",
    ],
    "fast" => [
        "@d1 p\"bd hh sn hh\" |> fast(2)        # twice as fast",
        "@d1 p\"bd hh\" |> every(4, fast(3))    # triplet every 4th cycle",
    ],
    "slow" => [
        "@d1 p\"bd sn cp ~\" |> slow(2)         # spread across 2 cycles",
    ],
    "every" => [
        "@d1 p\"bd hh sn hh\" |> every(4, rev)  # reverse every 4th cycle",
        "@d1 p\"bd hh sn hh\" |> every(3, fast(2))",
    ],
    "rev" => [
        "@d1 p\"bd hh sn hh\" |> rev            # hh sn hh bd",
    ],
    "stack" => [
        "@d1 stack(p\"bd*4\", p\"~ cp ~ cp\")     # layered drums",
    ],
    "cat" => [
        "@d1 cat([p\"bd*4\", p\"bd ~ bd ~\"])   # alternate beats each cycle",
    ],
    "mask" => [
        "@d1 mask(p\"bd*8\", p\"1 0 1 1 0 1 0 1\")  # gate the kicks",
    ],
    "" => [
        "@d1 p\"bd ~ sn ~\"            # 4 events per cycle",
        "@d1 p\"[bd bd] ~ sn ~\"       # nested = same time, two kicks",
        "@d1 p\"bd <hh sn cp> bd ~\"   # < > alternates each cycle",
    ],
    "gate" => [
        "@d1 gate(:bd, p\"1 0 1 0 1 0 1 0\")",
    ],
    "@dN" => [
        "@d1 p\"bd*4\"                  # slot d1",
        "@d2 p\"hh hh hh hh\" |> gain(0.4)",
        "# @d1 …                        # commented = muted, key `m` toggles",
    ],
)

"""
    _STARTER_PACKS

Genre starter sketches. Each value is a list of buffer lines that
replace the current buffer when the user runs `:starter <genre>`.
Keep each pack short (5-8 lines) — they're a starting point, not a
finished track.
"""
const _STARTER_PACKS = Dict{String,Vector{String}}(
    "house" => [
        "cps!(0.5)",
        "",
        "@d1 gate(:super808, p\"1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0\") |> n(-12) |> release(0.4) |> gain(1.4)",
        "@d2 gate(:supersnare, p\"0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0\") |> gain(0.9) |> room(0.2)",
        "@d3 p\"hh*8\" |> gain(0.35) |> hpf(4000) |> pan(p\"0.4 -0.4\")",
        "@d4 p\"superreese*2\" |> n(p\"-12 -7\") |> release(0.6) |> gain(1.0) |> lpf(800)",
    ],
    "witchhouse" => [
        "cps!(0.2)",
        "",
        "@d1 gate(:super808, p\"1 0 0 1 0 0 1 0\") |> n(-12) |> release(0.6) |> gain(1.6) |> room(0.3) |> shape(0.3)",
        "@d2 gate(:supersnare, p\"0 0 1 0\") |> n(-8) |> release(0.8) |> gain(0.7) |> room(0.7) |> lpf(2000)",
        "@d3 p\"hh*8\" |> speed(0.5) |> gain(0.4) |> hpf(3500) |> room(0.3)",
        "@d4 p\"superreese*4\" |> n(-24) |> release(0.8) |> gain(1.4) |> lpf(180) |> shape(0.5)",
        "@d5 p\"superhammond*2\" |> n(p\"-12 -5 -8 -3\") |> release(2.5) |> attack(0.5) |> gain(0.5) |> lpf(1200) |> room(0.6)",
    ],
    "ambient" => [
        "cps!(0.15)",
        "",
        "@d1 p\"superhammond\" |> n(p\"-12 -5 -8 -3 0 -3 -5 -8\") |> release(4.0) |> attack(1.0) |> gain(0.4) |> lpf(800) |> room(0.85) |> delay(0.4)",
        "@d2 p\"superfork\" |> n(p\"24 19 12 19 24 19 12 24\") |> release(3.0) |> gain(0.3) |> room(0.9)",
        "@d3 p\"supersine*1\" |> n(-36) |> release(8.0) |> gain(0.5) |> lpf(120) |> shape(0.2)",
    ],
    "trap" => [
        "cps!(0.4)",
        "",
        "@d1 gate(:super808, p\"1 0 0 1 0 0 0 1\") |> n(-12) |> release(0.5) |> gain(1.6)",
        "@d2 gate(:supersnare, p\"0 0 1 0\") |> gain(1.0) |> room(0.15)",
        "@d3 p\"hh*16\" |> gain(0.3) |> hpf(5000) |> pan(p\"0.3 -0.3 0.1 -0.1\")",
        "@d4 p\"super808\" |> n(p\"-24 -22 -19 -17\") |> release(1.0) |> gain(1.3) |> lpf(250) |> shape(0.4)",
    ],
    "lofi" => [
        "cps!(0.42)",
        "",
        "@d1 gate(:super808, p\"1 0 0 1\") |> gain(1.2) |> shape(0.3) |> lpf(2000)",
        "@d2 gate(:supersnare, p\"0 0 1 0\") |> gain(0.7) |> hpf(200) |> lpf(3000) |> room(0.4)",
        "@d3 p\"hh*4\" |> gain(0.3) |> hpf(2500) |> lpf(6000)",
        "@d4 p\"superhammond*2\" |> n(p\"0 -5 -8 -3\") |> release(1.5) |> gain(0.5) |> lpf(1800) |> room(0.5) |> crush(7)",
    ],

    # ── EDM expansion: cover the most-streamed subgenres that weren't
    # represented in the original 5 packs. Each pack still aims for
    # 5-7 lines — a starting point with kick + perc + bass + something
    # melodic, not a finished arrangement.
    "dubstep" => [
        "cps!(0.34)",   # ~140 BPM half-time feel",
        "",
        "@d1 gate(:super808, p\"1 0 0 0 0 0 0 0\") |> n(-12) |> release(0.6) |> gain(1.6)",
        "@d2 gate(:supersnare, p\"0 0 0 0 1 0 0 0\") |> gain(1.0) |> room(0.25) |> shape(0.2)",
        "@d3 p\"hh*8\" |> gain(0.25) |> hpf(5500) |> degradeBy(0.2)",
        "@d4 p\"superreese*2\" |> n(p\"<-12 -10 -8 -10>\") |> release(0.5) |> gain(1.4) |> lpf(p\"<400 1600 800 2400>\") |> shape(0.4)",
        "@d5 p\"~ ~ cp ~ ~ ~ cp ~\" |> gain(0.6) |> room(0.4)",
    ],
    "amapiano" => [
        "cps!(0.46)",   # ~112 BPM",
        "",
        "@d1 gate(:super808, p\"1 0 0 0 1 0 0 0\") |> n(-12) |> release(0.5) |> gain(1.4)",
        "@d2 p\"~ ~ cp ~ ~ ~ cp ~\" |> gain(0.7) |> room(0.3)",
        "@d3 p\"hh*16\" |> gain(0.3) |> hpf(4500) |> degradeBy(0.15)",
        "@d4 p\"superpiano*4\" |> n(p\"0 -3 5 7\") |> release(0.6) |> gain(0.55) |> room(0.4) |> degradeBy(0.3)",
        "@d5 :superreese |> n(p\"<-12 -10 -7 -5>\") |> release(0.8) |> gain(1.0) |> lpf(900) |> pump(8, 0.5)",
    ],
    "jungle" => [
        "cps!(0.7)",    # ~168 BPM",
        "",
        "@d1 p\"amen*2\" |> gain(1.2) |> speed(1.1) |> shape(0.2)",
        "@d2 gate(:super808, p\"1 0 0 0 0 0 1 0\") |> n(-12) |> release(0.5) |> gain(1.4)",
        "@d3 p\"~ ~ cp ~\" |> gain(0.6) |> room(0.4) |> shape(0.3)",
        "@d4 :superreese |> n(p\"-24 -19 -17 -12\") |> release(1.5) |> gain(1.0) |> lpf(p\"<500 1500>\")",
        "@d5 p\"hh*16\" |> gain(0.2) |> hpf(7000) |> degradeBy(0.3)",
    ],
    "idm" => [
        "cps!(0.55)",
        "",
        "@d1 p\"bd(3,8,<0 1 2>)\" |> gain(1.2)",
        "@d2 p\"cp(5,16,<2 4>)\" |> gain(0.7) |> room(0.3)",
        "@d3 p\"hh(11,16)\" |> gain(0.3) |> hpf(6000) |> degradeBy(0.4) |> pan(p\"<0 0.7 0.3 -0.5>\")",
        "@d4 :supersaw |> n(p\"0 7 5 ? 12 ?\") |> release(0.3) |> gain(0.6) |> lpf(p\"<300 1800 600>\") |> shape(0.3)",
        "@d5 p\"glitch ~ ~ glitch\" |> gain(0.5) |> sometimes(rev) |> crush(6)",
    ],
    "hardcore" => [
        "cps!(0.85)",   # 200+ BPM",
        "",
        "@d1 p\"k909*4\" |> gain(1.6) |> shape(0.6)",
        "@d2 gate(:supersnare, p\"0 0 1 0\") |> gain(1.2) |> room(0.2) |> shape(0.4)",
        "@d3 p\"hh*16\" |> gain(0.4) |> hpf(8000)",
        "@d4 :supersaw |> n(p\"<-12 -8 -5 -10>\") |> release(0.4) |> gain(1.3) |> lpf(p\"<400 2000 800>\") |> shape(0.5)",
        "@d5 p\"~ ~ ~ ~ cp ~ ~ ~\" |> gain(0.9) |> shape(0.4)",
    ],

    # ── Curated additions — common genre idioms documented in the
    #    TidalCycles tutorial (tidalcycles.org/docs, CC-BY-SA 4.0,
    #    Alex McLean et al.) and the AlgoRave community resources.
    #    Adapted to Ressac's combinator surface.
    "dub-techno" => [
        "# Dub techno — Basic Channel / Maurizio idiom",
        "# (long-decay delays + offset chord stab + minimal kick)",
        "cps!(0.5)",
        "",
        "@d1 p\"bd bd bd bd\" |> gain(1.0)",
        "@d2 p\"~ ~ cp ~\" |> gain(0.5) |> room(0.6)",
        "@d3 :supersaw |> n(p\"<-12 -10 -7>\") |> release(0.4) |> gain(0.45) |> lpf(900) |> delay(0.7) |> delaytime(0.5) |> delayfeedback(0.7) |> room(0.6)",
        "@d4 p\"hh ~ ~ ~ hh ~ ~ ~\" |> gain(0.3) |> hpf(6000)",
    ],
    "breakbeat" => [
        "# Breakbeat — classic 'Amen' chop idiom",
        "# (commonly taught in the Tidal tutorial as the breaks starter)",
        "cps!(0.56)",
        "",
        "@d1 p\"amencutup*4\" |> n(p\"<0 1 2 3 4 5>\") |> gain(1.2)",
        "@d2 gate(:super808, p\"1 0 0 0 0 0 0 0\") |> n(-12) |> release(0.4) |> gain(1.3)",
        "@d3 p\"~ ~ cp ~\" |> gain(0.7) |> room(0.3)",
        "@d4 :superreese |> n(p\"<-15 -12 -10>\") |> release(0.7) |> gain(0.8) |> lpf(p\"<600 1500>\")",
    ],
    "2step" => [
        "# UK 2-step garage — the syncopated kick + swung snare idiom",
        "# (Wookie/MJ Cole/Todd Edwards era, mid-90s UK)",
        "cps!(0.55)",
        "",
        "@d1 p\"bd ~ ~ bd ~ ~ bd ~\" |> gain(1.2)",
        "@d2 p\"~ ~ cp ~ ~ ~ ~ cp\" |> gain(0.8) |> room(0.3)",
        "@d3 p\"~ hh ~ hh ~ hh ~ hh\" |> gain(0.4) |> hpf(5000)",
        "@d4 :superpiano*2 |> n(p\"0 5 7 12\") |> release(0.3) |> gain(0.5) |> room(0.4)",
        "@d5 :superreese |> n(p\"<-12 -10 -7 -10>\") |> release(0.4) |> gain(0.7) |> lpf(800)",
    ],

    # ── Round B — three more starters documented as canonical
    #    genre templates in the AlgoRave + Tidal community.
    "juke" => [
        "# Juke / 160bpm Chicago ghetto-house — fast hats, tight kicks",
        "# (RP Boo / DJ Rashad lineage, AlgoRave repertoire).",
        "cps!(0.66)",
        "",
        "@d1 p\"bd ~ bd ~ ~ ~ bd ~ ~ ~ bd ~ ~ ~ ~ ~\" |> gain(1.3)",
        "@d2 p\"~ ~ ~ ~ cp ~ ~ ~ ~ cp ~ ~ ~ ~ cp ~\" |> gain(0.7) |> room(0.2)",
        "@d3 p\"hh*16\" |> gain(0.35) |> hpf(6000)",
        "@d4 p\"~ ~ vox ~ ~ ~ vox ~\" |> speed(p\"<1 0.85 1.2 1>\") |> gain(0.5)",
        "@d5 :supersaw |> n(p\"-5 -7 -10 ?\") |> release(0.2) |> gain(0.5)",
    ],
    "liquid-dnb" => [
        "# Liquid drum & bass — smooth pad, rolling break, sub on 1+3",
        "# (LTJ Bukem / Calibre lineage — 174 BPM half-time feel)",
        "cps!(0.72)",
        "",
        "@d1 p\"bd ~ ~ ~ ~ ~ sn ~ ~ ~ bd ~ ~ ~ sn ~\" |> gain(1.2)",
        "@d2 p\"hh*16\" |> gain(0.3) |> hpf(5500) |> degradeBy(0.1)",
        "@d3 :subdrop |> n(p\"0 ~ ~ ~ 0 ~ 5 ~\") |> release(1.2) |> gain(0.8)",
        "@d4 :softpad |> n(p\"<0 5 7 3>\") |> release(2.0) |> attack(0.3) |> gain(0.35) |> room(0.6)",
        "@d5 p\"~ ~ ~ cp ~ ~ ~ ~\" |> gain(0.6) |> room(0.5)",
    ],
    "vaporwave" => [
        "# Vaporwave — slow, lush, A E S T H E T I C",
        "# (chopped samples + soft pad + tape wobble idiom)",
        "cps!(0.26)",
        "",
        "@d1 p\"bd ~ ~ bd ~ ~ ~ ~\" |> gain(1.1) |> lpf(2000)",
        "@d2 p\"~ ~ cp ~ ~ ~ ~ ~\" |> gain(0.6) |> room(0.5)",
        "@d3 :softpad |> n(p\"<0 -3 -5 -7>\") |> release(3.0) |> attack(0.8) |> gain(0.45) |> room(0.85) |> delay(0.3)",
        "@d4 :superpiano |> n(p\"<7 5 3 0>*2\") |> release(1.5) |> gain(0.4) |> room(0.6) |> crush(8)",
        "@d5 :subdrop |> n(p\"-12 ~ ~ -12\") |> release(1.5) |> gain(0.6) |> lpf(150)",
    ],

    # ── Chaos & reservoir starters (see wiki 14-chaos-reservoir) ──
    # Each demonstrates one mode of using the chaos / reservoir plugins
    # as pattern sources. Hit E to eval everything once SC is up.
    "chaos" => [
        "# Chaos-driven modulation — control-rate Pattern{Float64}",
        "# generators piped into SuperDirt params.",
        "cps!(0.5)",
        "",
        "# Hénon map glitches the kick speed every step",
        "@d1 p\"bd ~ sn ~\" |> set(:speed, Chaos.henon() |> range_pat(0.9, 1.2))",
        "",
        "# Lorenz attractor sweeps a supersaw filter",
        "@d2 :supersaw |> n(p\"0 3 5 7\") |> set(:cutoff, Chaos.lorenz() |> range_pat(400, 3500)) |> gain(0.6)",
        "",
        "# Logistic map (chaos edge) pans a sub",
        "@d3 :super808 |> n(p\"<-12 -10 -8 -10>\") |> set(:pan, Chaos.logistic(r=3.95) |> range_pat(-0.8, 0.8)) |> release(0.6) |> gain(1.2)",
    ],
    "reservoir-spike" => [
        "# Route I — AdEx bursting reservoir → percussive sinebursts",
        "# layout-mapped to a minor pentatonic.",
        "cps!(0.5)",
        "",
        "r = Reservoir.adex(N=32, params=Reservoir.ADEX_BURSTING, seed=42)",
        "",
        "@d1 Reservoir.spike_burst(r; drive=600.0, layout=:scale, layout_args=(scale=:minor_pentatonic, root=220), burst_dur=1//16) |> gain(0.4)",
        "",
        "# Anchor with a kick so the chaos has a pulse",
        "@d2 p\"bd ~ ~ ~ bd ~ ~ ~\" |> gain(1.3)",
        "@d3 p\"hh*8\" |> gain(0.25) |> hpf(4000)",
    ],
    "reservoir-spectral" => [
        "# Route II — RECA rule 110 over harmonic partials.",
        "# Rule 110 is Turing-complete (edge of chaos). Try 30 (fully",
        "# chaotic), 90 (Sierpinski), 184 (traffic) for very different",
        "# spectra.",
        "cps!(0.4)",
        "",
        "r = Reservoir.reca(N=16, rule=110, init=:single)",
        "",
        "@d1 Reservoir.spectral_cloud(r; frames_per_cycle=8, layout=:harmonic, layout_args=(fund=110,)) |> gain(0.55)",
        "",
        "@d2 p\"~ ~ cp ~\" |> gain(0.5) |> room(0.4)",
    ],
    "reservoir-mix" => [
        "# All three routes at once — spikes fire notes, a separate",
        "# reservoir's neuron drives a filter cutoff, drums anchor it.",
        "cps!(0.45)",
        "",
        "r1 = Reservoir.adex(N=24, params=Reservoir.ADEX_BURSTING, seed=7)",
        "r2 = Reservoir.adex(N=8, seed=11)",
        "",
        "@d1 Reservoir.spike_burst(r1; drive=600.0, layout=:scale, layout_args=(scale=:dorian, root=110)) |> gain(0.4)",
        "",
        "@d2 :supersaw |> n(p\"0 ~ 5 ~ 7 ~ 3 ~\") |> set(:cutoff, Reservoir.modulator(r2, neuron=5, drive=500.0) |> range_pat(600, 3500)) |> gain(0.5)",
        "",
        "@d3 p\"bd ~ ~ ~ bd ~ ~ ~\" |> gain(1.3)",
        "@d4 p\"~ ~ cp ~\" |> gain(0.5) |> room(0.3)",
    ],

    # ── Discover-by-tweaking starters: every keyword arg surfaced ──
    # The user reads the comments, changes values in place, hears the
    # effect of each parameter without leaving the buffer.
    "chaos-explore" => [
        "# ╭─ chaos generators — modify any value to hear the effect ─╮",
        "# │  Each Chaos.* returns a Pattern{Float64} plugged into",
        "# │  set(:k, …). Compose with range_pat / segment / slow / fast.",
        "# ╰────────────────────────────────────────────────────────────╯",
        "cps!(0.5)",
        "",
        "# ── Lorenz attractor (3D continuous) ──────────────────────",
        "# σ ρ β = strength of each axis coupling (canonical chaos: 10/28/8÷3)",
        "#   try ρ=14 → stable orbit, ρ=99 → wider chaos",
        "# dt    = Euler step (smaller = smoother, slower)",
        "# axis  = :x (-25..25)  :y (-30..30)  :z (0..60)",
        "# steps_per_cycle = sampling rate within one Ressac cycle",
        "# init  = (x₀, y₀, z₀) initial state",
        "@d1 :supersaw |> n(p\"0 3 5 7\") |> set(:cutoff,",
        "    Chaos.lorenz(σ=10, ρ=28, β=8/3, dt=0.01, axis=:x,",
        "                  steps_per_cycle=100, init=(0.1, 0.0, 0.0))",
        "    |> range_pat(400, 4000)) |> gain(0.5)",
        "",
        "# ── Hénon map (2D discrete) — sharp, glitchy ───────────────",
        "# a b   = canonical chaos a=1.4 b=0.3 ; a=1.06 = periodic",
        "# axis  = :x (-1.5..1.5) or :y",
        "@d2 p\"bd ~ sn ~\" |> set(:speed,",
        "    Chaos.henon(a=1.4, b=0.3, axis=:x,",
        "                 steps_per_cycle=64, init=(0.1, 0.0))",
        "    |> range_pat(0.9, 1.2))",
        "",
        "# ── Logistic map (1D) — r selects regime ───────────────────",
        "# r ∈ (0,4]: r<3 = fixed point ; r=3..3.57 = period doubling",
        "#            r>3.57 = chaos ; r=3.83 = period-3 window ; r=4 = max chaos",
        "# init must be in (0, 1) strictly",
        "@d3 :super808 |> n(p\"<-12 -10 -8 -10>\") |> set(:pan,",
        "    Chaos.logistic(r=3.9, steps_per_cycle=64, init=0.5)",
        "    |> range_pat(-0.8, 0.8)) |> release(0.6) |> gain(1.2)",
        "",
        "# ── Rössler attractor (3D continuous) — smoother loop ──────",
        "# a b c = a=0.2 b=0.2 c=5.7 chaotic ; c=2 stable spiral",
        "# (uncomment to add a 4th voice)",
        "# @d4 :superpiano |> n(p\"0 7 12\") |> set(:speed,",
        "#     Chaos.rossler(a=0.2, b=0.2, c=5.7, dt=0.05, axis=:x,",
        "#                    steps_per_cycle=100, init=(0.1, 0.0, 0.0))",
        "#     |> range_pat(0.8, 1.5)) |> gain(0.5)",
        "",
        "# ── Standard map (Chirikov) — area-preserving ──────────────",
        "# K     = K≈0.971635 is the KAM threshold (just-chaotic)",
        "# axis  = :p (momentum, unbounded) or :θ (angle [0, 2π))",
        "# (uncomment to add a 5th voice)",
        "# @d5 :superhammond |> n(p\"<0 5 7 12>\") |> set(:gain,",
        "#     Chaos.standard(K=0.971635, axis=:p,",
        "#                     steps_per_cycle=64, init=(0.1, 0.1))",
        "#     |> range_pat(0.3, 0.9))",
        "",
        "# ── Anchor ─────────────────────────────────────────────────",
        "@d9 p\"hh*8\" |> gain(0.2) |> hpf(4000)",
    ],
    "reservoir-mic" => [
        "# ╭─ Voice / mic / line input drives the reservoir ─╮",
        "# │  1) `:audio-in start`  → starts SC's mic listener",
        "# │  2) eval the buffer    → reservoir pilots a melody",
        "# │  3) parle / chante     → V monte avec ton volume,",
        "# │                          le réseau spike en sync",
        "# ╰────────────────────────────────────────────────────╯",
        "cps!(0.5)",
        "",
        "# Bring up the audio-in bridge (does nothing without SC running).",
        "# In the TUI command line: `:audio-in start`  (et stop pour libérer)",
        "",
        "# Reservoir with cortical-style noise so the mic input pushes",
        "# already-near-threshold neurons over the edge.",
        "r = Reservoir.adex(N=24, params=Reservoir.ADEX_BURSTING,",
        "                   σ_noise=400.0, seed=42)",
        "",
        "# drive=:audio_in pulls the latest RMS amplitude from the mic",
        "# (scaled to pA). Quiet input → almost silent ; loud → dense spikes.",
        "@d1 Reservoir.pool_burst(r;",
        "    bins=8, frames_per_cycle=8,",
        "    layout=:scale, layout_args=(scale=:minor_pentatonic, root=220),",
        "    drive=:audio_in,",
        "    gain_per_spike=0.05, max_gain=0.7) |> gain(0.5)",
        "",
        "# Anchor with a kick so silence vs voice contrast is audible.",
        "@d9 p\"bd ~ ~ ~ bd ~ ~ ~\" |> gain(1.2)",
    ],
    "reservoir-wta" => [
        "# ╭─ Winner-takes-all — séquence mono d'un seul neurone à la fois ─╮",
        "# │  Mêmes neurones AdEx, mêmes dynamiques, mais 1 spike max",
        "# │  reported par step → mélodie monophonique au lieu d'accords",
        "# │  empilés. Le 'gagnant' = celui avec V le plus haut just",
        "# │  avant reset.",
        "# ╰────────────────────────────────────────────────────────────────╯",
        "cps!(0.5)",
        "",
        "r = Reservoir.adex(N=12, params=Reservoir.ADEX_REGULAR_BURST,",
        "                   σ_noise=400.0, wta=true, seed=42)",
        "",
        "@d1 Reservoir.spike_burst(r;",
        "    drive=500.0,",
        "    layout=:scale, layout_args=(scale=:minor_pentatonic, root=220),",
        "    burst_dur=1//8) |> gain(0.5)",
        "",
        "@d9 p\"bd ~ ~ ~ bd ~ ~ ~\" |> gain(1.2)",
    ],
    "reservoir-meanfield" => [
        "# ╭─ Wilson-Cowan mean field — limit-cycle population ─╮",
        "# │  Au lieu de N neurones indépendants, deux scalaires",
        "# │  E (excitateurs) et I (inhibiteurs) qui s'oscillent",
        "# │  mutuellement. Les 'spikes' visibles aux routes sont",
        "# │  sampled Bernoulli depuis E ou I selon le neurone.",
        "# │  Tweaker τE, τI, wEE/wEI pour changer le régime.",
        "# ╰──────────────────────────────────────────────────────╯",
        "cps!(0.5)",
        "",
        "r = Reservoir.meanfield(N=24, inhibitory_fraction=0.3,",
        "                        τE=10.0, τI=20.0,",
        "                        wEE=12, wEI=10, wIE=12, wII=2,",
        "                        seed=1)",
        "",
        "# Drive modeste — laisse le limit-cycle se manifester",
        "@d1 Reservoir.pool_burst(r;",
        "    bins=8, frames_per_cycle=8,",
        "    layout=:scale, layout_args=(scale=:dorian, root=110),",
        "    drive=300.0,",
        "    gain_per_spike=0.05) |> gain(0.5)",
        "",
        "# Module aussi un cutoff via E (rate excitatrice)",
        "@d2 :supersaw |> n(p\"0 ~ 5 ~ 7 ~ 3 ~\") |>",
        "   set(:cutoff, Reservoir.modulator(r, kind=:E, drive=400.0)",
        "                |> range_pat(400, 4000)) |> gain(0.5)",
        "",
        "@d9 p\"bd ~ ~ ~ bd ~ ~ ~\" |> gain(1.2)",
    ],
    "reservoir-coupled" => [
        "# ╭─ E/I coupled populations ─╮",
        "# │  Excitatory pool drives inhibitory pool;",
        "# │  inhibitory pool damps the excitatory pool.",
        "# │  E/I balance = comme cortex biologique.",
        "# ╰──────────────────────────────╯",
        "cps!(0.5)",
        "",
        "r_E = Reservoir.adex(N=24, params=Reservoir.ADEX_REGULAR_BURST,",
        "                     σ_noise=400.0, seed=1)",
        "r_I = Reservoir.adex(N=6,  params=Reservoir.ADEX_FAST,",
        "                     σ_noise=300.0, seed=2)",
        "",
        "# E and I in one group; output_idx=1 → routes lisent r_E",
        "g = Reservoir.couple([r_E, r_I]; output_idx=1)",
        "",
        "# Excitateurs activent inhibiteurs (E → I)",
        "Reservoir.connect!(g, 1, 2; gain=300, p_connect=0.3, sign=:positive)",
        "",
        "# Inhibiteurs amortissent excitateurs (I → E)",
        "Reservoir.connect!(g, 2, 1; gain=400, p_connect=0.4, sign=:negative)",
        "",
        "@d1 Reservoir.pool_burst(g;",
        "    bins=8, frames_per_cycle=8,",
        "    layout=:scale, layout_args=(scale=:dorian, root=110),",
        "    drive=500.0,",
        "    gain_per_spike=0.05) |> gain(0.5)",
        "",
        "@d9 p\"bd ~ ~ ~ bd ~ ~ ~\" |> gain(1.2)",
    ],
    "reservoir-pool" => [
        "# ╭─ tonal pool — neurones votent pour des notes ─╮",
        "# │  N neurones → K tons. Multiple spikes sur le même",
        "# │  bin → gain accumulé. Fluctuations de tonalité",
        "# │  + volume par ton émergent du réseau.",
        "# ╰─────────────────────────────────────────────────╯",
        "cps!(0.5)",
        "",
        "# AdEx bursting + noise → activité riche pour alimenter le pool",
        "r = Reservoir.adex(N=32, params=Reservoir.ADEX_BURSTING,",
        "                   σ_noise=400.0, seed=42)",
        "",
        "# 8 bins pentatoniques mineurs depuis 110 Hz. frames_per_cycle=8",
        "# donne une nouvelle 'voix' (gain accumulé) tous les 1/8 de cycle.",
        "@d1 Reservoir.pool_burst(r;",
        "    bins=8,",
        "    frames_per_cycle=8,",
        "    layout=:scale, layout_args=(scale=:minor_pentatonic, root=110),",
        "    drive=500.0,",
        "    gain_per_spike=0.06,",
        "    max_gain=0.7,",
        "    burst_dur=1//16) |> gain(0.5)",
        "",
        "# Anchor",
        "@d9 p\"bd ~ ~ ~ bd ~ ~ ~\" |> gain(1.2)",
    ],
    "reservoir-noisy" => [
        "# ╭─ noisy baseline + pattern drive — neurons sync to beats ─╮",
        "# │  σ_noise pushes V near threshold continuously. When a",
        "# │  pattern event injects a pulse, the population spikes",
        "# │  in synchrony. Pure cortical computing vibes.",
        "# ╰────────────────────────────────────────────────────────────╯",
        "cps!(0.5)",
        "",
        "# OU baseline (σ_noise pA, τ_noise ms) — try σ=200 quiet, 500 alive, 800 saturated",
        "r = Reservoir.adex(N=16, seed=42, σ_noise=500.0, τ_noise=20.0)",
        "",
        "# The drum pattern is injected as DRIVE — each event pulses a neuron",
        "# (neuron index = hash(event.value) % N). The reservoir spikes back",
        "# in synchrony, mapped to a pentatonic via the layout.",
        "@d1 Reservoir.spike_burst(r;",
        "    drive = p\"bd ~ sn ~ ~ bd ~ sn ~\",",
        "    layout = :scale,",
        "    layout_args = (scale=:minor_pentatonic, root=220),",
        "    burst_dur = 1//16) |> gain(0.4)",
        "",
        "# Layer the actual drums underneath the spikes for the lock-in feel",
        "@d2 p\"bd ~ sn ~ ~ bd ~ sn ~\" |> gain(1.2)",
        "",
        "# Hat for steady motion",
        "@d3 p\"hh*8\" |> gain(0.2) |> hpf(5000)",
    ],
    "reservoir-rate" => [
        "# ╭─ Route V — spike rate AS frequency ─╮",
        "# │  On compte les spikes par neurone et par frame, on",
        "# │  convertit en Hz, et on commande un oscillateur avec.",
        "# │  Si un neurone spike à 200 Hz → tu entends 200 Hz.",
        "# │  4 shapes : :impulse (clic brut), :saw, :sin, :pulse.",
        "# ╰───────────────────────────────────────╯",
        "cps!(0.5)",
        "",
        "# Reservoir actif avec du bruit pour qu'il spike fort.",
        "# steps_per_cycle=2000 → résolution temporelle fine (1ms à 0.5cps),",
        "# nécessaire pour capter des taux jusqu'à ~kHz.",
        "r = Reservoir.adex(N=32, params=Reservoir.ADEX_FAST,",
        "                   dt=0.5, steps_per_cycle=2000,",
        "                   σ_noise=600.0, τ_noise=15.0,",
        "                   inhibitory_fraction=0.2, seed=7)",
        "",
        "# 4 voix → 4 neurones spécifiques. Chacun pilote un Saw.",
        "# freq_scale=1.0 → Hz brut. freq_offset=80 → drone baseline.",
        "# smoothing_frames=4 → moyenne mobile, pitch moins jittery.",
        "@d1 Reservoir.rate_voice(r;",
        "    sources=[3, 11, 17, 25],",
        "    shape=:saw,",
        "    frames_per_cycle=24,",
        "    freq_scale=1.0, freq_offset=80.0,",
        "    lo_freq=60.0, hi_freq=2000.0,",
        "    gain=0.22, overlap=2.5,",
        "    smoothing_frames=4,",
        "    drive=Reservoir.drive_const(350.0)) |> gain(0.55)",
        "",
        "# Pulse layer sur 2 autres neurones, transposé une octave plus haut.",
        "@d2 Reservoir.rate_voice(r;",
        "    sources=[5, 19],",
        "    shape=:pulse,",
        "    frames_per_cycle=16,",
        "    freq_scale=2.0, freq_offset=120.0,",
        "    gain=0.15, overlap=2.0,",
        "    smoothing_frames=2,",
        "    drive=Reservoir.drive_const(300.0)) |> gain(0.45) |> hpf(400)",
        "",
        "@d9 p\"bd ~ ~ ~ bd ~ ~ ~\" |> gain(1.2)",
        "",
        "# Essaie : shape=:impulse pour buzz brut, :sin pour rendu doux.",
        "# Augmente freq_scale → transpose plus haut. freq_offset → drone fixe.",
        "# Baisse smoothing_frames=0 pour entendre le jitter des spikes.",
    ],
    "reservoir-pop5" => [
        "# ╭─ 5 populations interconnectées qui se répondent ─╮",
        "# │  5 sous-réservoirs aux paramètres différents (donc",
        "# │  fréquences propres différentes) couplés en boucle.",
        "# │  Chaque pop devient une voix avec sa freq émergente.",
        "# │  Si les couplages déstabilisent → polyphonie qui",
        "# │  évolue. Si trop forts → tout sync sur une fréquence.",
        "# ╰────────────────────────────────────────────────────╯",
        "cps!(0.5)",
        "",
        "# Cinq pops, chacune avec son régime AdEx + son seed.",
        "# steps_per_cycle=2000 partout → cohérence du couplage.",
        "p_A = Reservoir.adex(N=12, params=Reservoir.ADEX_TONIC,",
        "                     dt=1.0, steps_per_cycle=800,",
        "                     σ_noise=400.0, seed=1)",
        "p_B = Reservoir.adex(N=12, params=Reservoir.ADEX_ADAPTING,",
        "                     dt=1.0, steps_per_cycle=800,",
        "                     σ_noise=350.0, seed=2)",
        "p_C = Reservoir.adex(N=12, params=Reservoir.ADEX_REGULAR_BURST,",
        "                     dt=1.0, steps_per_cycle=800,",
        "                     σ_noise=300.0, seed=3)",
        "p_D = Reservoir.adex(N=12, params=Reservoir.ADEX_FAST,",
        "                     dt=1.0, steps_per_cycle=800,",
        "                     σ_noise=450.0, seed=4)",
        "p_E = Reservoir.adex(N=12, params=Reservoir.ADEX_IRREGULAR,",
        "                     dt=1.0, steps_per_cycle=800,",
        "                     σ_noise=380.0, seed=5)",
        "",
        "# Couplage en anneau A→B→C→D→E→A, plus deux raccourcis",
        "# pour casser la symétrie (A→C inhibitrice, D→A excitatrice).",
        "g = Reservoir.couple([p_A, p_B, p_C, p_D, p_E]; output_idx=1)",
        "Reservoir.connect!(g, 1, 2; gain=180, p_connect=0.25, sign=:positive)",
        "Reservoir.connect!(g, 2, 3; gain=180, p_connect=0.25, sign=:positive)",
        "Reservoir.connect!(g, 3, 4; gain=180, p_connect=0.25, sign=:positive)",
        "Reservoir.connect!(g, 4, 5; gain=180, p_connect=0.25, sign=:positive)",
        "Reservoir.connect!(g, 5, 1; gain=200, p_connect=0.25, sign=:positive)",
        "Reservoir.connect!(g, 1, 3; gain=150, p_connect=0.20, sign=:negative)",
        "Reservoir.connect!(g, 4, 1; gain=120, p_connect=0.20, sign=:positive)",
        "",
        "# Une voix rate_voice par population. Chaque pop = un groupe de neurones",
        "# (indices DANS LE GROUPE COUPLÉ → 1..12 pour A, 13..24 pour B, …).",
        "@d1 Reservoir.rate_voice(g;",
        "    sources=[collect(1:12), collect(13:24), collect(25:36),",
        "             collect(37:48), collect(49:60)],",
        "    shape=:saw,",
        "    frames_per_cycle=16,",
        "    freq_scale=1.5, freq_offset=60.0,",
        "    lo_freq=55.0, hi_freq=1600.0,",
        "    gain=0.12, overlap=2.5,",
        "    smoothing_frames=3,",
        "    drive=Reservoir.drive_const(280.0)) |> gain(0.7)",
        "",
        "# Anchor",
        "@d9 p\"bd ~ ~ ~ bd ~ ~ ~\" |> gain(1.0)",
        "",
        "# Live tweaks : change σ_noise d'une pop pour pousser sa freq.",
        "# Change le gain d'une connect! → bascule lock-in / chaos.",
        "# Visualise avec :scope reservoir-graph (montre les 5 pops + edges).",
    ],
    "reservoir-explore" => [
        "# ╭─ reservoir — every knob exposed, eval lines selectively ─╮",
        "# │  AdEx neurons + RECA cellular automaton, three routes.",
        "# │  Hit `e` on the line / block you want. Change params live,",
        "# │  hit `e` again — cascade re-eval rewires @dN automatically.",
        "# ╰────────────────────────────────────────────────────────────╯",
        "cps!(0.5)",
        "",
        "# ── AdEx reservoir construction ────────────────────────────",
        "# N                    = number of neurons (8..256 reasonable)",
        "# params               = AdExParams. Built-in regimes (Brette & Gerstner 2005):",
        "#                        ADEX_TONIC          steady rate, no adaptation",
        "#                        ADEX_ADAPTING       fast burst, slows down",
        "#                        ADEX_INITIAL_BURST  onset burst then quiet",
        "#                        ADEX_REGULAR_BURST  periodic bursts",
        "#                        ADEX_DELAYED_ACCEL  pause then ramp up",
        "#                        ADEX_DELAYED_BURST  pause then bursts",
        "#                        ADEX_TRANSIENT      brief onset then stops",
        "#                        ADEX_IRREGULAR      chaotic dynamics",
        "#                        ADEX_REGULAR / ADEX_BURSTING / ADEX_FAST  (originals)",
        "# dt                   = simulator timestep in ms (0.5..2.0)",
        "# steps_per_cycle      = events per cycle (200..2000 — denser = more notes)",
        "# p_connect            = synaptic connectivity (0..1, default 0.1)",
        "# W_gain               = synapse weight scale in pA per spike (100..500)",
        "# V_init               = :rest (uniform) or :scattered (less synchronous)",
        "# σ_noise              = OU baseline noise volatility (pA, 0=silent, 500+ lively)",
        "# τ_noise              = OU correlation time (ms, 20 cortical-typical)",
        "# inhibitory_fraction  = 0..1, fraction whose outgoing synapses",
        "#                        are forced negative (Dale's, 0.2 cortical)",
        "# seed                 = reproducible random connectivity",
        "r_lead = Reservoir.adex(N=24, params=Reservoir.ADEX_FAST,",
        "                        dt=1.0, steps_per_cycle=500,",
        "                        p_connect=0.1, W_gain=180.0,",
        "                        V_init=:scattered,",
        "                        σ_noise=400.0, τ_noise=20.0,",
        "                        inhibitory_fraction=0.2,",
        "                        seed=42)",
        "",
        "# ── Route I — spike → sineburst ────────────────────────────",
        "# Each spike on neuron i fires a percussive sine at freqs[i].",
        "# drive       = ANY of:",
        "#                 Real           — constant current (0 silent, 400+ active)",
        "#                 Vector         — static per-neuron drive (length=N)",
        "#                 Function       — (cycle, step) → Real or Vector",
        "#                 Pattern{Sym}   — p\"bd ~ sn ~\" pulses neurons on events",
        "#                 Pattern{Flt}   — continuous signal broadcast per-cycle",
        "#                 String         — auto-parses to Pattern{Sym}",
        "# Helper functions (step units; multiply by spc for cycle units):",
        "#   drive_const(amp)                            — same as bare Real",
        "#   drive_sin(amp, period; offset, phase)       — sine wave",
        "#   drive_square(amp, period; duty, offset)     — on/off pulse train",
        "#   drive_tri(amp, period; offset)              — triangle",
        "#   drive_ramp(low, high, period)               — sawtooth",
        "#   drive_burst(amp, on_steps, every_steps)     — periodic bursts",
        "#   drive_sum(d1, d2, ...)                      — additive layering",
        "# Ex: drive = drive_sum(drive_const(400), drive_sin(200, 500))",
        "@d1 Reservoir.spike_burst(r_lead;",
        "    drive=500.0,",
        "    layout=:scale,",
        "    layout_args=(scale=:minor_pentatonic, root=220),",
        "    burst_dur=1//16,",
        "    gain=0.3,",
        "    synth=:sineburst) |> gain(0.4)",
        "",
        "# layout cheat-sheet:",
        "#   :logfreq  → log-uniform between lo, hi   (layout_args = (;))",
        "#   :scale    → musical scale degrees       (layout_args = (scale=:dorian, root=110))",
        "#                scales: :minor_pentatonic :major_pentatonic :dorian :phrygian",
        "#                        :lydian :mixolydian :natural_minor :harmonic_minor",
        "#                        :whole_tone :chromatic  (+ many more in Ressac._SCALES)",
        "#   :harmonic → i · fund                    (layout_args = (fund=110,))",
        "#   :cluster  → dense around center         (layout_args = (center=880, spread=0.2))",
        "",
        "# ── RECA reservoir (cellular automaton) ────────────────────",
        "# rule  = Wolfram rule 0..255 :  30 chaos · 90 Sierpinski · 110 edge",
        "#                                184 traffic · 54 class-IV complex",
        "# N     = cells (16..256)",
        "# init  = :single (one cell on), :rand (50%), :zero (need input)",
        "r_reca = Reservoir.reca(N=24, rule=110, init=:rand,",
        "                        boundary=:wrap, steps_per_cycle=8, seed=7)",
        "",
        "@d2 Reservoir.spike_burst(r_reca;",
        "    layout=:harmonic, layout_args=(fund=110,),",
        "    burst_dur=1//32, gain=0.25) |> gain(0.4)",
        "",
        "# ── Route II — spectral cloud (additive resynthesis) ───────",
        "# Instead of one sine per spike, fire one CHORD of 16 partials",
        "# per frame, with each partial's amplitude driven by a neuron.",
        "# Result: an evolving pad / drone whose spectrum tracks the",
        "# reservoir state. Great for textures, not for rhythm.",
        "#",
        "# bins              = partial count (must match SynthDef — 16 ships built-in)",
        "# frames_per_cycle  = chord refresh rate per cycle (4..16, 8 default)",
        "# layout            = same as Route I — applied to the 16 bins",
        "# amplitude_kind    = which state drives amps: :auto (V for AdEx, bit for RECA)",
        "#                     :V :w :spike :density :bit",
        "# amplitude_scale   = post-transform fn; :auto clip-normalises into [0,1]",
        "# overlap           = envelope sustain ×  (1.0=abut, 2.0=50% xfade)",
        "# drive             = same as Route I (any form)",
        "r_spec = Reservoir.reca(N=16, rule=30, init=:rand, steps_per_cycle=16)",
        "@d3 Reservoir.spectral_cloud(r_spec;",
        "    bins=16,",
        "    frames_per_cycle=8,",
        "    layout=:harmonic, layout_args=(fund=110,),",
        "    amplitude_kind=:auto, amplitude_scale=:auto,",
        "    overlap=2.0, gain=0.3) |> gain(0.3)",
        "",
        "# ── Route III — scalar modulator ───────────────────────────",
        "# Read ONE neuron's state as a continuous control signal.",
        "# Plugs into `set(:any_param, …)` like sine() or perlin() —",
        "# you're using neural dynamics to modulate any synth param.",
        "#",
        "# neuron  = which to read (1..N)",
        "# kind    = :auto (V for AdEx, bit for RECA) · :V :w :spike :density :bit",
        "# scale   = post-transform fn (identity by default, e.g. abs, x->x/70)",
        "# drive   = same as Route I (any form) — keeps neurons active",
        "r_mod = Reservoir.adex(N=8, σ_noise=400.0, seed=99)",
        "@d4 :supersaw |> n(p\"0 ~ 5 ~ 7 ~ 3 ~\") |> set(:cutoff,",
        "    Reservoir.modulator(r_mod, neuron=3, kind=:V,",
        "                         scale=identity, drive=500.0)",
        "    |> range_pat(400, 4000)) |> gain(0.5)",
        "",
        "# ── Anchor ──────────────────────────────────────────────────",
        "@d9 p\"bd ~ ~ ~ bd ~ ~ ~\" |> gain(1.3)",
        "@d10 p\"hh*8\" |> gain(0.2) |> hpf(4000)",
    ],
)
